---
name: CI

'on': [push]

env:
  LIBGIT2_VERSION: 1.3.2

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install libgit2
        run: |
          wget --progress=dot https://github.com/libgit2/libgit2/archive/v${LIBGIT2_VERSION}.tar.gz
          tar -zxf v${LIBGIT2_VERSION}.tar.gz
          mkdir libgit-build
          cd libgit-build
          cmake -DCMAKE_VERBOSE_MAKEFILE=ON ../libgit2-${LIBGIT2_VERSION}
          cmake --build .
          sudo cmake --build . --target install
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Run Tests
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        run: ./run-tests.lisp
